// <auto-generated />
using BackendOfMajorProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackendOfMajorProject.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BackendOfMajorProject.Models.BankDetail", b =>
                {
                    b.Property<int>("BankDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BranchName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ifsc")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SystemUserDetailId")
                        .HasColumnType("int");

                    b.HasKey("BankDetailId");

                    b.HasIndex("SystemUserDetailId")
                        .IsUnique();

                    b.ToTable("BankDetails");
                });

            modelBuilder.Entity("BackendOfMajorProject.Models.BookingDetail", b =>
                {
                    b.Property<int>("BookingDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("FareDetails")
                        .HasColumnType("float");

                    b.Property<int>("FlightDetailId")
                        .HasColumnType("int");

                    b.Property<string>("SeatNo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SelectedClass")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SystemUserDetailId")
                        .HasColumnType("int");

                    b.HasKey("BookingDetailId");

                    b.HasIndex("FlightDetailId");

                    b.HasIndex("SystemUserDetailId");

                    b.ToTable("BookingDetails");
                });

            modelBuilder.Entity("BackendOfMajorProject.Models.ClassDetail", b =>
                {
                    b.Property<int>("ClassDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BusinessClassCapacity")
                        .HasColumnType("int");

                    b.Property<double>("BusinessClassPrice")
                        .HasColumnType("float");

                    b.Property<int>("EconomyClassCapacity")
                        .HasColumnType("int");

                    b.Property<double>("EconomyClassPrice")
                        .HasColumnType("float");

                    b.Property<int>("PremiumClassCapacity")
                        .HasColumnType("int");

                    b.Property<double>("PremiumClassPrice")
                        .HasColumnType("float");

                    b.Property<int>("PremiumEconomyClassCapacity")
                        .HasColumnType("int");

                    b.Property<double>("PremiumEconomyClassPrice")
                        .HasColumnType("float");

                    b.HasKey("ClassDetailId");

                    b.ToTable("ClassDetails");
                });

            modelBuilder.Entity("BackendOfMajorProject.Models.FlightDetail", b =>
                {
                    b.Property<int>("FlightDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArrivalTime")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("ClassDetailId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DepartureTime")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Distance")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("From")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("To")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("FlightDetailId");

                    b.HasIndex("ClassDetailId");

                    b.ToTable("FlightDetails");
                });

            modelBuilder.Entity("BackendOfMajorProject.Models.FlightsAnnualReport", b =>
                {
                    b.Property<int>("FlightsAnnualReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AirAsia")
                        .HasColumnType("float");

                    b.Property<double>("AirIndia")
                        .HasColumnType("float");

                    b.Property<double>("AllianceAir")
                        .HasColumnType("float");

                    b.Property<double>("IndiGo")
                        .HasColumnType("float");

                    b.Property<double>("Kingfisher")
                        .HasColumnType("float");

                    b.Property<double>("SpiceJet")
                        .HasColumnType("float");

                    b.HasKey("FlightsAnnualReportId");

                    b.ToTable("flightsAnnualReports");
                });

            modelBuilder.Entity("BackendOfMajorProject.Models.PassengersDetail", b =>
                {
                    b.Property<int>("PassengersDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AadharNo")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Email")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("LastName")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Mobile")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("PassportNo")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("SystemUserDetailId")
                        .HasColumnType("int");

                    b.HasKey("PassengersDetailId");

                    b.HasIndex("SystemUserDetailId");

                    b.ToTable("PassengersDetails");
                });

            modelBuilder.Entity("BackendOfMajorProject.Models.SystemUserDetail", b =>
                {
                    b.Property<int>("SystemUserDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AadharDetails")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Email")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Gender")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("LastName")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Mobile")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("PassportDetails")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Password")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("RegisteredOrNot")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SystemUserDetailId");

                    b.ToTable("SystemUserDetails");
                });

            modelBuilder.Entity("BackendOfMajorProject.Models.BankDetail", b =>
                {
                    b.HasOne("BackendOfMajorProject.Models.SystemUserDetail", "SystemUserDetail")
                        .WithOne("BankDetail")
                        .HasForeignKey("BackendOfMajorProject.Models.BankDetail", "SystemUserDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemUserDetail");
                });

            modelBuilder.Entity("BackendOfMajorProject.Models.BookingDetail", b =>
                {
                    b.HasOne("BackendOfMajorProject.Models.FlightDetail", "FlightDetail")
                        .WithMany("BookingDetail")
                        .HasForeignKey("FlightDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendOfMajorProject.Models.SystemUserDetail", "SystemUserDetail")
                        .WithMany("BookingDetail")
                        .HasForeignKey("SystemUserDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlightDetail");

                    b.Navigation("SystemUserDetail");
                });

            modelBuilder.Entity("BackendOfMajorProject.Models.FlightDetail", b =>
                {
                    b.HasOne("BackendOfMajorProject.Models.ClassDetail", "ClassDetail")
                        .WithMany("FlightDetail")
                        .HasForeignKey("ClassDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassDetail");
                });

            modelBuilder.Entity("BackendOfMajorProject.Models.PassengersDetail", b =>
                {
                    b.HasOne("BackendOfMajorProject.Models.SystemUserDetail", "SystemUserDetail")
                        .WithMany("PassengersDetail")
                        .HasForeignKey("SystemUserDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemUserDetail");
                });

            modelBuilder.Entity("BackendOfMajorProject.Models.ClassDetail", b =>
                {
                    b.Navigation("FlightDetail");
                });

            modelBuilder.Entity("BackendOfMajorProject.Models.FlightDetail", b =>
                {
                    b.Navigation("BookingDetail");
                });

            modelBuilder.Entity("BackendOfMajorProject.Models.SystemUserDetail", b =>
                {
                    b.Navigation("BankDetail");

                    b.Navigation("BookingDetail");

                    b.Navigation("PassengersDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
